# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use the latest stable golang 1.20 to compile to a binary
FROM --platform=$BUILDPLATFORM golang:1.22 as build

WORKDIR /work
COPY . .

ARG TARGETOS
ARG TARGETARCH
ARG GO_LD_FLAGS

RUN go get ./...
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags "${GO_LD_FLAGS}" -o bin/manager main.go


# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot@sha256:6a3500b086c2856fbc189f5d11351bdbcf7c4dc5673c2b6070aac9d607da90d7

# For multi-arch builds, use automatic platform build arguments
# see https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
ARG TARGETOS
ARG TARGETARCH

WORKDIR /
USER 65532:65532
COPY --from=build --chown=nonroot "/work/bin/manager" "/manager"
COPY "./ThirdPartyLicenses" "/ThirdPartyLicenses"
COPY "./LICENSE" "/LICENSE"
ENTRYPOINT ["/manager"]
