# permissions for end users to edit authproxyworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authproxyworkload-editor-role
rules:
- apiGroups:
  - cloudsql.cloud.google.com
  resources:
  - authproxyworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudsql.cloud.google.com
  resources:
  - authproxyworkloads/status
  verbs:
  - get
