# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Run this from your dev environment:
#  gcloud builds submit --project=cloud-sql-connectors --config=.build/release.yaml --substitutions=_TEST_BUILD_ID=0000-dirty-$(date "+%s")
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - 'tools/publish-installer.sh'
    id: 'publish_installer'
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: make
    args:
      - '-f'
      - 'operator.mk'
      - build_push_docker
    id: 'publish_container'
options:
  env:
    - "RELEASE_TEST_BUILD_ID=$_TEST_BUILD_ID"
    - "RELEASE_COMMIT_SHA=$COMMIT_SHA"
    - "RELEASE_TAG_NAME=$TAG_NAME"
    - "IS_RELEASE_BUILD=true"
substitutions:
  _TEST_BUILD_ID: ""
