# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Run this from your dev environment:
#  gcloud builds submit --project=cloud-sql-connectors --config=.build/release.yaml --substitutions=_TEST_BUILD_ID=0000-dirty-$(date "+%s")
steps:
  - name: gcr.io/cloud-sql-connectors/builders/cloud-sql-operator-builder
    entrypoint: make
    args:
      - release
    id: 'build-release'
options:
  env:
    - "RELEASE_TEST_BUILD_ID=$_TEST_BUILD_ID"
    - "RELEASE_COMMIT_SHA=$COMMIT_SHA"
    - "RELEASE_TAG_NAME=$TAG_NAME"
substitutions:
  # _TEST_BUILD_ID is used exclusively for release process development.
  # Always leave this blank for prod releases
  _TEST_BUILD_ID: ""
